import { inter } from "@/constants/styles/general";
import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/shared/Providers";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Script
            src="https://kit.fontawesome.com/ea8db09c1f.js"
            crossOrigin="anonymous"
            strategy="lazyOnload"
          />
          <Script id="load-devicon-css" strategy="afterInteractive">
            {`
              const link = document.createElement('link');
              link.rel = 'stylesheet';
              link.href = 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css';
              document.head.appendChild(link);
            `}
          </Script>
          {children}
        </Providers>
      </body>
    </html>
  );
}
